train_config:
  num_cells: 128
  x_min: -1.0
  x_max: 1.0
  y_min: -1.0
  y_max: 1.0
  dt: 0.01
  batch_size: 100
  record: 1
  roll_out:
   - 1
   - 10
   - 50
   - 100

data_config:
  Advection2D-4.0:
    data_path: '/home/gaoch/dataset/advection1D/1D_Advection_Sols_beta4.0.hdf5'
    params:
      vx: 1.5625
      vy: 0.78125
      bc: 'periodic'
  # Advection1D-0.1: 
  #   data_path: '/home/gaoch/dataset/advection1D/1D_Advection_Sols_beta0.1.hdf5'
  #   params:
  #     beta: 0.1

  # Advection1D-0.2:
  #   data_path: '/home/gaoch/dataset/advection1D/1D_Advection_Sols_beta0.2.hdf5'
  #   params:
  #     beta: 0.2

  # Advection1D-0.4:
  #   data_path: '/home/gaoch/dataset/advection1D/1D_Advection_Sols_beta0.4.hdf5'
  #   params:
  #     beta: 0.4

  # Advection1D-0.7:
  #   data_path: '/home/gaoch/dataset/advection1D/1D_Advection_Sols_beta0.7.hdf5'
  #   params:
  #     beta: 0.7

  # Advection1D-1.0:
  #   data_path: '/home/gaoch/dataset/advection1D/1D_Advection_Sols_beta1.0.hdf5'
  #   params:
  #     beta: 1.0

  # Advection1D-2.0:
  #   data_path: '/home/gaoch/dataset/advection1D/1D_Advection_Sols_beta2.0.hdf5'
  #   params:
  #     beta: 2.0


  # Advection1D-7.0:
  #   data_path: '/home/gaoch/dataset/advection1D/1D_Advection_Sols_beta7.0.hdf5'
  #   params:
  #     beta: 7.0
    