
    
Burgers1D-0.01:
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu0.01.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 0.01

Burgers1D-0.001:
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu0.001.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 0.001

Burgers1D-0.002:
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu0.002.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 0.002

Burgers1D-0.004:
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu0.004.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 0.004



Burgers1D-0.02:
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu0.02.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 0.02

Burgers1D-0.04:
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu0.04.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 0.04

Burgers1D-0.1:
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu0.1.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 0.1
  
Burgers1D-0.2:
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu0.2.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 0.2

Burgers1D-0.4:
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu0.4.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 0.4

Burgers1D-1.0:
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu1.0.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 1.0

Burgers1D-2.0:
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu2.0.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 2.0

Burgers1D-4.0: 
  data_path: '/home/gaoch/dataset/burgers1D/1D_Burgers_Sols_Nu4.0.hdf5'
  num_cells: 1024
  x_min: -1.0
  x_max: 1.0
  dt: 0.001
  record: 20
  batch_size: 1000
  params:
    nu: 4.0