train_config:
  num_cells: 1024
  x_min: 0.0
  x_max: 1.0
  dt: 0.0001
  batch_size: 1000
  record: 50000
  roll_out:
   - 1
   - 10
   - 100
   - 200

data_config:
  DiffusionSorption1D:
    data_path: '/home/gaoch/dataset/diffusionsorption1D/1D_diff-sorp_NA_NA.h5'
    params:
      D: 0.0005
      phi: 0.29
      rho_s: 2880
      k: 3.5e-4
      nf: 0.874
      bc: 'periodic'
  