ReactionDiffusion1D-0.5-10:
  data_path: '/home/gaoch/dataset/reactiondiffusion1D/ReacDiff_Nu0.5_Rho10.0.hdf5'
  num_cells: 1024
  record: 50000
  x_min: 0.0
  x_max: 1.0
  dt: 0.0000002
  batch_size: 100
  params:
    nu: 0.5
    rho: 10.05