train_config:
  num_cells: 128
  x_min: -1.0
  x_max: 1.0
  y_min: -1.0
  y_max: 1.0
  dt: 0.05
  batch_size: 100
  record: 1
  roll_out:
   - 1
   - 10
   - 50
   - 100

data_config: 
  ReactionDiffusion2D:
    data_path: '/home/gaoch/dataset/reactiondiffusion1D/ReacDiff_Nu0.5_Rho1.0.hdf5'
    params:
      Du: 0.001
      Dv: 0.005
      k: 0.005
      bc: 'periodic'