train_config:
  num_cells: 1024
  x_min: 0.0
  x_max: 1.0
  dt: 0.0000002
  batch_size: 5000
  record: 50000
  roll_out:
   - 50
   - 1
   - 10
   - 100

data_config: 
  ReactionDiffusion1D-0.5-1:
    data_path: '/home/gaoch/dataset/reactiondiffusion1D/ReacDiff_Nu0.5_Rho1.0.hdf5'
    params:
      nu: 0.5
      rho: 1
      bc: 'periodic'